### PR TITLE
Null roles

### PR DESCRIPTION
**Pull request by samrees**
This is to match the behavior of `fly` in setting roles. I found when setting a team with just "owners" in terraform, if I queried the authentication with fly i would get back things like:
```
  "pipeline-operator": {
      "groups": null,
      "users": null
    },
```
which in non-json would display as:
```
name/role                   users                   groups
operator/pipeline-operator  all                     none
```

So this does not set a value in the atc.Team struct for either user or groups if we don't receive one for terraform, fixing the bug.

### CODE REVIEW

**Comment by tlwr** [comment]
Hi, I'm going to take a look at this and make the integration tests pass

**Comment by samrees** [comment]
Unfortunately the integration tests seem to test a bunch of the bad behavior I fixed.

**Comment by katieschilling** [comment]
will this be merged soon @tlwr ? We'd like to see this change as well.

**Comment by tlwr** [comment]
Sorry I dropped the ball on this!

**Pull request merged**
